apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: Metadata
    verbs: [ "create" ]
    resources:
      - group: ""
        resources: [ "pods" ]
  - level: Metadata
    verbs: [ "delete" ]
    resources:
      - group: ""
        resources: [ "pods" ]
