apiVersion: v1
kind: Pod
metadata:
  name: readonly-nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      securityContext:
        readOnlyRootFilesystem: true
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-log
          mountPath: /var/log/nginx
  volumes:
    - name: nginx-cache
      emptyDir: {}
    - name: nginx-log
      emptyDir: {}
