apiVersion: v1
kind: Pod
metadata:
  name: host-network-pod
  namespace: default
spec:
  hostNetwork: true
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 8080
          hostPort: 8080
