apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-test
  namespace: sa-demo
---
apiVersion: v1
kind: Pod
metadata:
  name: sa-test
  namespace: sa-demo
spec:
  serviceAccountName: sa-test
  containers:
  - name: sa-test
    image: nginx:latest
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sa-test-role
  namespace: sa-demo
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-test-rolebinding
  namespace: sa-demo
subjects:
- kind: ServiceAccount
  name: sa-test
roleRef:
  kind: Role
  name: sa-test-role
  apiGroup: rbac.authorization.k8s.io
