apiVersion: v1
kind: Pod
metadata:
  name: default-pod
  labels:
    app: default-pod
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: default-seccomp
    image: busybox:1.28
    command: [ "sh", "-c", "echo 'Using Default Seccomp Profile!' && sleep 1h" ]
    securityContext:
      allowPrivilegeEscalation: false
