apiVersion: v1
kind: Namespace
metadata:
  name: secure-app
  labels:
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Pod
metadata:
  name: secure-app
  namespace: secure-app
spec:
  containers:
  - image: busybox:latest
    name: busybox-enforce-restrict
    command: ["sh", "-c", "sleep 3600"]
    securityContext:
      allowPrivilegeEscalation: true
---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: busybox-enforce-restrict
#   namespace: psa-enforce-restrict
# spec:
#   containers:
#   - image: busybox:latest
#     name: busybox-enforce-restrict
#     command: ["sh", "-c", "sleep 3600"]
#     securityContext:
#       allowPrivilegeEscalation: false
#       capabilities:
#         drop: ["ALL"]
#       runAsNonRoot: true
#       seccompProfile:
#         type: RuntimeDefault
---