apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  namespace: default
spec:
  containers:
  - name: secret-container
    image: busybox:latest
    command: ["/bin/sh", "-c", "sleep 3600"]
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: cks-test
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: cks-test
          key: password
