---
apiVersion: v1
kind: Pod
metadata:
  name: webpage
  labels:
    app: webpage
spec:
  containers:
  - name: webpage
    image: httpd:latest
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: webpage
  labels:
    app: webpage
spec:
  containers:
  - name: webpage
    image: httpd:latest
    ports:
    - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webpage-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - webpage.localhost
    secretName: webpage-tls-secret
  rules:
  - host: webpage.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webpage-service
            port:
              number: 80

