apiVersion: v1
kind: Pod
metadata:
  name: busybox-secret
spec:
  containers:
  - name: busybox-secret
    image: busybox:latest
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: secret-volume
      mountPath: "/etc/secrets"
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: cks-test
